########################################################################

# Root where is esp-open-sdk is installed. 
ROOT       = /home/nando/tools/esp-open-sdk
# Verbose 1 show info make process
VERBOSE   = 0

# include Makefile
include ../../Esp8266-open-sdk.mk
